// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: proto/automationv1/automation.proto

package automationv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AutomationService_SearchItem_FullMethodName         = "/muxcore.automation.v1.AutomationService/SearchItem"
	AutomationService_Dispatch_FullMethodName           = "/muxcore.automation.v1.AutomationService/Dispatch"
	AutomationService_AddToQueue_FullMethodName         = "/muxcore.automation.v1.AutomationService/AddToQueue"
	AutomationService_GetQueue_FullMethodName           = "/muxcore.automation.v1.AutomationService/GetQueue"
	AutomationService_RemoveFromQueue_FullMethodName    = "/muxcore.automation.v1.AutomationService/RemoveFromQueue"
	AutomationService_GetHistory_FullMethodName         = "/muxcore.automation.v1.AutomationService/GetHistory"
	AutomationService_SearchNow_FullMethodName          = "/muxcore.automation.v1.AutomationService/SearchNow"
	AutomationService_ListBlocklist_FullMethodName      = "/muxcore.automation.v1.AutomationService/ListBlocklist"
	AutomationService_ClearBlocklist_FullMethodName     = "/muxcore.automation.v1.AutomationService/ClearBlocklist"
	AutomationService_BlocklistRelease_FullMethodName   = "/muxcore.automation.v1.AutomationService/BlocklistRelease"
	AutomationService_RetryImport_FullMethodName        = "/muxcore.automation.v1.AutomationService/RetryImport"
	AutomationService_ListDelayProfiles_FullMethodName  = "/muxcore.automation.v1.AutomationService/ListDelayProfiles"
	AutomationService_UpsertDelayProfile_FullMethodName = "/muxcore.automation.v1.AutomationService/UpsertDelayProfile"
	AutomationService_ListCutoffUnmet_FullMethodName    = "/muxcore.automation.v1.AutomationService/ListCutoffUnmet"
)

// AutomationServiceClient is the client API for AutomationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AutomationServiceClient interface {
	SearchItem(ctx context.Context, in *SearchItemRequest, opts ...grpc.CallOption) (*SearchItemResponse, error)
	Dispatch(ctx context.Context, in *DispatchRequest, opts ...grpc.CallOption) (*DispatchResponse, error)
	AddToQueue(ctx context.Context, in *AddToQueueRequest, opts ...grpc.CallOption) (*AddToQueueResponse, error)
	GetQueue(ctx context.Context, in *GetQueueRequest, opts ...grpc.CallOption) (*GetQueueResponse, error)
	RemoveFromQueue(ctx context.Context, in *RemoveFromQueueRequest, opts ...grpc.CallOption) (*RemoveFromQueueResponse, error)
	GetHistory(ctx context.Context, in *GetHistoryRequest, opts ...grpc.CallOption) (*GetHistoryResponse, error)
	SearchNow(ctx context.Context, in *SearchNowRequest, opts ...grpc.CallOption) (*SearchNowResponse, error)
	ListBlocklist(ctx context.Context, in *ListBlocklistRequest, opts ...grpc.CallOption) (*ListBlocklistResponse, error)
	ClearBlocklist(ctx context.Context, in *ClearBlocklistRequest, opts ...grpc.CallOption) (*ClearBlocklistResponse, error)
	BlocklistRelease(ctx context.Context, in *BlocklistReleaseRequest, opts ...grpc.CallOption) (*BlocklistReleaseResponse, error)
	RetryImport(ctx context.Context, in *RetryImportRequest, opts ...grpc.CallOption) (*RetryImportResponse, error)
	ListDelayProfiles(ctx context.Context, in *ListDelayProfilesRequest, opts ...grpc.CallOption) (*ListDelayProfilesResponse, error)
	UpsertDelayProfile(ctx context.Context, in *UpsertDelayProfileRequest, opts ...grpc.CallOption) (*UpsertDelayProfileResponse, error)
	ListCutoffUnmet(ctx context.Context, in *ListCutoffUnmetRequest, opts ...grpc.CallOption) (*ListCutoffUnmetResponse, error)
}

type automationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAutomationServiceClient(cc grpc.ClientConnInterface) AutomationServiceClient {
	return &automationServiceClient{cc}
}

func (c *automationServiceClient) SearchItem(ctx context.Context, in *SearchItemRequest, opts ...grpc.CallOption) (*SearchItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchItemResponse)
	err := c.cc.Invoke(ctx, AutomationService_SearchItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationServiceClient) Dispatch(ctx context.Context, in *DispatchRequest, opts ...grpc.CallOption) (*DispatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DispatchResponse)
	err := c.cc.Invoke(ctx, AutomationService_Dispatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationServiceClient) AddToQueue(ctx context.Context, in *AddToQueueRequest, opts ...grpc.CallOption) (*AddToQueueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddToQueueResponse)
	err := c.cc.Invoke(ctx, AutomationService_AddToQueue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationServiceClient) GetQueue(ctx context.Context, in *GetQueueRequest, opts ...grpc.CallOption) (*GetQueueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetQueueResponse)
	err := c.cc.Invoke(ctx, AutomationService_GetQueue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationServiceClient) RemoveFromQueue(ctx context.Context, in *RemoveFromQueueRequest, opts ...grpc.CallOption) (*RemoveFromQueueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveFromQueueResponse)
	err := c.cc.Invoke(ctx, AutomationService_RemoveFromQueue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationServiceClient) GetHistory(ctx context.Context, in *GetHistoryRequest, opts ...grpc.CallOption) (*GetHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHistoryResponse)
	err := c.cc.Invoke(ctx, AutomationService_GetHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationServiceClient) SearchNow(ctx context.Context, in *SearchNowRequest, opts ...grpc.CallOption) (*SearchNowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchNowResponse)
	err := c.cc.Invoke(ctx, AutomationService_SearchNow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationServiceClient) ListBlocklist(ctx context.Context, in *ListBlocklistRequest, opts ...grpc.CallOption) (*ListBlocklistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBlocklistResponse)
	err := c.cc.Invoke(ctx, AutomationService_ListBlocklist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationServiceClient) ClearBlocklist(ctx context.Context, in *ClearBlocklistRequest, opts ...grpc.CallOption) (*ClearBlocklistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClearBlocklistResponse)
	err := c.cc.Invoke(ctx, AutomationService_ClearBlocklist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationServiceClient) BlocklistRelease(ctx context.Context, in *BlocklistReleaseRequest, opts ...grpc.CallOption) (*BlocklistReleaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlocklistReleaseResponse)
	err := c.cc.Invoke(ctx, AutomationService_BlocklistRelease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationServiceClient) RetryImport(ctx context.Context, in *RetryImportRequest, opts ...grpc.CallOption) (*RetryImportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetryImportResponse)
	err := c.cc.Invoke(ctx, AutomationService_RetryImport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationServiceClient) ListDelayProfiles(ctx context.Context, in *ListDelayProfilesRequest, opts ...grpc.CallOption) (*ListDelayProfilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDelayProfilesResponse)
	err := c.cc.Invoke(ctx, AutomationService_ListDelayProfiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationServiceClient) UpsertDelayProfile(ctx context.Context, in *UpsertDelayProfileRequest, opts ...grpc.CallOption) (*UpsertDelayProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertDelayProfileResponse)
	err := c.cc.Invoke(ctx, AutomationService_UpsertDelayProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationServiceClient) ListCutoffUnmet(ctx context.Context, in *ListCutoffUnmetRequest, opts ...grpc.CallOption) (*ListCutoffUnmetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCutoffUnmetResponse)
	err := c.cc.Invoke(ctx, AutomationService_ListCutoffUnmet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AutomationServiceServer is the server API for AutomationService service.
// All implementations must embed UnimplementedAutomationServiceServer
// for forward compatibility.
type AutomationServiceServer interface {
	SearchItem(context.Context, *SearchItemRequest) (*SearchItemResponse, error)
	Dispatch(context.Context, *DispatchRequest) (*DispatchResponse, error)
	AddToQueue(context.Context, *AddToQueueRequest) (*AddToQueueResponse, error)
	GetQueue(context.Context, *GetQueueRequest) (*GetQueueResponse, error)
	RemoveFromQueue(context.Context, *RemoveFromQueueRequest) (*RemoveFromQueueResponse, error)
	GetHistory(context.Context, *GetHistoryRequest) (*GetHistoryResponse, error)
	SearchNow(context.Context, *SearchNowRequest) (*SearchNowResponse, error)
	ListBlocklist(context.Context, *ListBlocklistRequest) (*ListBlocklistResponse, error)
	ClearBlocklist(context.Context, *ClearBlocklistRequest) (*ClearBlocklistResponse, error)
	BlocklistRelease(context.Context, *BlocklistReleaseRequest) (*BlocklistReleaseResponse, error)
	RetryImport(context.Context, *RetryImportRequest) (*RetryImportResponse, error)
	ListDelayProfiles(context.Context, *ListDelayProfilesRequest) (*ListDelayProfilesResponse, error)
	UpsertDelayProfile(context.Context, *UpsertDelayProfileRequest) (*UpsertDelayProfileResponse, error)
	ListCutoffUnmet(context.Context, *ListCutoffUnmetRequest) (*ListCutoffUnmetResponse, error)
	mustEmbedUnimplementedAutomationServiceServer()
}

// UnimplementedAutomationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAutomationServiceServer struct{}

func (UnimplementedAutomationServiceServer) SearchItem(context.Context, *SearchItemRequest) (*SearchItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchItem not implemented")
}
func (UnimplementedAutomationServiceServer) Dispatch(context.Context, *DispatchRequest) (*DispatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Dispatch not implemented")
}
func (UnimplementedAutomationServiceServer) AddToQueue(context.Context, *AddToQueueRequest) (*AddToQueueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddToQueue not implemented")
}
func (UnimplementedAutomationServiceServer) GetQueue(context.Context, *GetQueueRequest) (*GetQueueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetQueue not implemented")
}
func (UnimplementedAutomationServiceServer) RemoveFromQueue(context.Context, *RemoveFromQueueRequest) (*RemoveFromQueueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveFromQueue not implemented")
}
func (UnimplementedAutomationServiceServer) GetHistory(context.Context, *GetHistoryRequest) (*GetHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHistory not implemented")
}
func (UnimplementedAutomationServiceServer) SearchNow(context.Context, *SearchNowRequest) (*SearchNowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchNow not implemented")
}
func (UnimplementedAutomationServiceServer) ListBlocklist(context.Context, *ListBlocklistRequest) (*ListBlocklistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBlocklist not implemented")
}
func (UnimplementedAutomationServiceServer) ClearBlocklist(context.Context, *ClearBlocklistRequest) (*ClearBlocklistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClearBlocklist not implemented")
}
func (UnimplementedAutomationServiceServer) BlocklistRelease(context.Context, *BlocklistReleaseRequest) (*BlocklistReleaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BlocklistRelease not implemented")
}
func (UnimplementedAutomationServiceServer) RetryImport(context.Context, *RetryImportRequest) (*RetryImportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RetryImport not implemented")
}
func (UnimplementedAutomationServiceServer) ListDelayProfiles(context.Context, *ListDelayProfilesRequest) (*ListDelayProfilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDelayProfiles not implemented")
}
func (UnimplementedAutomationServiceServer) UpsertDelayProfile(context.Context, *UpsertDelayProfileRequest) (*UpsertDelayProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertDelayProfile not implemented")
}
func (UnimplementedAutomationServiceServer) ListCutoffUnmet(context.Context, *ListCutoffUnmetRequest) (*ListCutoffUnmetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCutoffUnmet not implemented")
}
func (UnimplementedAutomationServiceServer) mustEmbedUnimplementedAutomationServiceServer() {}
func (UnimplementedAutomationServiceServer) testEmbeddedByValue()                           {}

// UnsafeAutomationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AutomationServiceServer will
// result in compilation errors.
type UnsafeAutomationServiceServer interface {
	mustEmbedUnimplementedAutomationServiceServer()
}

func RegisterAutomationServiceServer(s grpc.ServiceRegistrar, srv AutomationServiceServer) {
	// If the following call panics, it indicates UnimplementedAutomationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AutomationService_ServiceDesc, srv)
}

func _AutomationService_SearchItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationServiceServer).SearchItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationService_SearchItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationServiceServer).SearchItem(ctx, req.(*SearchItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationService_Dispatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DispatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationServiceServer).Dispatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationService_Dispatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationServiceServer).Dispatch(ctx, req.(*DispatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationService_AddToQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddToQueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationServiceServer).AddToQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationService_AddToQueue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationServiceServer).AddToQueue(ctx, req.(*AddToQueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationService_GetQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationServiceServer).GetQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationService_GetQueue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationServiceServer).GetQueue(ctx, req.(*GetQueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationService_RemoveFromQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveFromQueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationServiceServer).RemoveFromQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationService_RemoveFromQueue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationServiceServer).RemoveFromQueue(ctx, req.(*RemoveFromQueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationService_GetHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationServiceServer).GetHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationService_GetHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationServiceServer).GetHistory(ctx, req.(*GetHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationService_SearchNow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchNowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationServiceServer).SearchNow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationService_SearchNow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationServiceServer).SearchNow(ctx, req.(*SearchNowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationService_ListBlocklist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBlocklistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationServiceServer).ListBlocklist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationService_ListBlocklist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationServiceServer).ListBlocklist(ctx, req.(*ListBlocklistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationService_ClearBlocklist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearBlocklistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationServiceServer).ClearBlocklist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationService_ClearBlocklist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationServiceServer).ClearBlocklist(ctx, req.(*ClearBlocklistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationService_BlocklistRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlocklistReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationServiceServer).BlocklistRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationService_BlocklistRelease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationServiceServer).BlocklistRelease(ctx, req.(*BlocklistReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationService_RetryImport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetryImportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationServiceServer).RetryImport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationService_RetryImport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationServiceServer).RetryImport(ctx, req.(*RetryImportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationService_ListDelayProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDelayProfilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationServiceServer).ListDelayProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationService_ListDelayProfiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationServiceServer).ListDelayProfiles(ctx, req.(*ListDelayProfilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationService_UpsertDelayProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertDelayProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationServiceServer).UpsertDelayProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationService_UpsertDelayProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationServiceServer).UpsertDelayProfile(ctx, req.(*UpsertDelayProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationService_ListCutoffUnmet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCutoffUnmetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationServiceServer).ListCutoffUnmet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationService_ListCutoffUnmet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationServiceServer).ListCutoffUnmet(ctx, req.(*ListCutoffUnmetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AutomationService_ServiceDesc is the grpc.ServiceDesc for AutomationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AutomationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "muxcore.automation.v1.AutomationService",
	HandlerType: (*AutomationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchItem",
			Handler:    _AutomationService_SearchItem_Handler,
		},
		{
			MethodName: "Dispatch",
			Handler:    _AutomationService_Dispatch_Handler,
		},
		{
			MethodName: "AddToQueue",
			Handler:    _AutomationService_AddToQueue_Handler,
		},
		{
			MethodName: "GetQueue",
			Handler:    _AutomationService_GetQueue_Handler,
		},
		{
			MethodName: "RemoveFromQueue",
			Handler:    _AutomationService_RemoveFromQueue_Handler,
		},
		{
			MethodName: "GetHistory",
			Handler:    _AutomationService_GetHistory_Handler,
		},
		{
			MethodName: "SearchNow",
			Handler:    _AutomationService_SearchNow_Handler,
		},
		{
			MethodName: "ListBlocklist",
			Handler:    _AutomationService_ListBlocklist_Handler,
		},
		{
			MethodName: "ClearBlocklist",
			Handler:    _AutomationService_ClearBlocklist_Handler,
		},
		{
			MethodName: "BlocklistRelease",
			Handler:    _AutomationService_BlocklistRelease_Handler,
		},
		{
			MethodName: "RetryImport",
			Handler:    _AutomationService_RetryImport_Handler,
		},
		{
			MethodName: "ListDelayProfiles",
			Handler:    _AutomationService_ListDelayProfiles_Handler,
		},
		{
			MethodName: "UpsertDelayProfile",
			Handler:    _AutomationService_UpsertDelayProfile_Handler,
		},
		{
			MethodName: "ListCutoffUnmet",
			Handler:    _AutomationService_ListCutoffUnmet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/automationv1/automation.proto",
}
