// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: proto/automationv1/automation.proto

package automationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchItemRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ItemType         string                 `protobuf:"bytes,1,opt,name=item_type,json=itemType,proto3" json:"item_type,omitempty"` // "movie" or "tv"
	Query            string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	TmdbId           int32                  `protobuf:"varint,3,opt,name=tmdb_id,json=tmdbId,proto3" json:"tmdb_id,omitempty"`
	Year             int32                  `protobuf:"varint,4,opt,name=year,proto3" json:"year,omitempty"`
	Season           int32                  `protobuf:"varint,5,opt,name=season,proto3" json:"season,omitempty"`
	Episode          int32                  `protobuf:"varint,6,opt,name=episode,proto3" json:"episode,omitempty"`
	Limit            int32                  `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty"`
	QualityProfileId string                 `protobuf:"bytes,8,opt,name=quality_profile_id,json=qualityProfileId,proto3" json:"quality_profile_id,omitempty"`
	Absolute         int32                  `protobuf:"varint,9,opt,name=absolute,proto3" json:"absolute,omitempty"`                       // anime absolute episode number
	SeriesType       string                 `protobuf:"bytes,10,opt,name=series_type,json=seriesType,proto3" json:"series_type,omitempty"` // "standard", "daily", or "anime"
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SearchItemRequest) Reset() {
	*x = SearchItemRequest{}
	mi := &file_proto_automationv1_automation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchItemRequest) ProtoMessage() {}

func (x *SearchItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_automationv1_automation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchItemRequest.ProtoReflect.Descriptor instead.
func (*SearchItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_automationv1_automation_proto_rawDescGZIP(), []int{0}
}

func (x *SearchItemRequest) GetItemType() string {
	if x != nil {
		return x.ItemType
	}
	return ""
}

func (x *SearchItemRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchItemRequest) GetTmdbId() int32 {
	if x != nil {
		return x.TmdbId
	}
	return 0
}

func (x *SearchItemRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *SearchItemRequest) GetSeason() int32 {
	if x != nil {
		return x.Season
	}
	return 0
}

func (x *SearchItemRequest) GetEpisode() int32 {
	if x != nil {
		return x.Episode
	}
	return 0
}

func (x *SearchItemRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchItemRequest) GetQualityProfileId() string {
	if x != nil {
		return x.QualityProfileId
	}
	return ""
}

func (x *SearchItemRequest) GetAbsolute() int32 {
	if x != nil {
		return x.Absolute
	}
	return 0
}

func (x *SearchItemRequest) GetSeriesType() string {
	if x != nil {
		return x.SeriesType
	}
	return ""
}

type SearchItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matches       []*ReleaseMatch        `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchItemResponse) Reset() {
	*x = SearchItemResponse{}
	mi := &file_proto_automationv1_automation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchItemResponse) ProtoMessage() {}

func (x *SearchItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_automationv1_automation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchItemResponse.ProtoReflect.Descriptor instead.
func (*SearchItemResponse) Descriptor() ([]byte, []int) {
	return file_proto_automationv1_automation_proto_rawDescGZIP(), []int{1}
}

func (x *SearchItemResponse) GetMatches() []*ReleaseMatch {
	if x != nil {
		return x.Matches
	}
	return nil
}

type ReleaseMatch struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Guid             string                 `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	Title            string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Size             int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Seeders          int32                  `protobuf:"varint,4,opt,name=seeders,proto3" json:"seeders,omitempty"`
	Peers            int32                  `protobuf:"varint,5,opt,name=peers,proto3" json:"peers,omitempty"`
	IndexerName      string                 `protobuf:"bytes,6,opt,name=indexer_name,json=indexerName,proto3" json:"indexer_name,omitempty"`
	DownloadUrl      string                 `protobuf:"bytes,7,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	InfoUrl          string                 `protobuf:"bytes,8,opt,name=info_url,json=infoUrl,proto3" json:"info_url,omitempty"`
	DownloadProtocol string                 `protobuf:"bytes,9,opt,name=download_protocol,json=downloadProtocol,proto3" json:"download_protocol,omitempty"`
	Score            int32                  `protobuf:"varint,10,opt,name=score,proto3" json:"score,omitempty"`
	Category         string                 `protobuf:"bytes,11,opt,name=category,proto3" json:"category,omitempty"`
	SubCategory      string                 `protobuf:"bytes,12,opt,name=sub_category,json=subCategory,proto3" json:"sub_category,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReleaseMatch) Reset() {
	*x = ReleaseMatch{}
	mi := &file_proto_automationv1_automation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseMatch) ProtoMessage() {}

func (x *ReleaseMatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_automationv1_automation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseMatch.ProtoReflect.Descriptor instead.
func (*ReleaseMatch) Descriptor() ([]byte, []int) {
	return file_proto_automationv1_automation_proto_rawDescGZIP(), []int{2}
}

func (x *ReleaseMatch) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

func (x *ReleaseMatch) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ReleaseMatch) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ReleaseMatch) GetSeeders() int32 {
	if x != nil {
		return x.Seeders
	}
	return 0
}

func (x *ReleaseMatch) GetPeers() int32 {
	if x != nil {
		return x.Peers
	}
	return 0
}

func (x *ReleaseMatch) GetIndexerName() string {
	if x != nil {
		return x.IndexerName
	}
	return ""
}

func (x *ReleaseMatch) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *ReleaseMatch) GetInfoUrl() string {
	if x != nil {
		return x.InfoUrl
	}
	return ""
}

func (x *ReleaseMatch) GetDownloadProtocol() string {
	if x != nil {
		return x.DownloadProtocol
	}
	return ""
}

func (x *ReleaseMatch) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ReleaseMatch) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ReleaseMatch) GetSubCategory() string {
	if x != nil {
		return x.SubCategory
	}
	return ""
}

type DispatchRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Guid             string                 `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	Title            string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	DownloadUrl      string                 `protobuf:"bytes,3,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	DownloadProtocol string                 `protobuf:"bytes,4,opt,name=download_protocol,json=downloadProtocol,proto3" json:"download_protocol,omitempty"`
	Size             int64                  `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	Score            int32                  `protobuf:"varint,6,opt,name=score,proto3" json:"score,omitempty"`
	IndexerName      string                 `protobuf:"bytes,7,opt,name=indexer_name,json=indexerName,proto3" json:"indexer_name,omitempty"`
	ItemType         string                 `protobuf:"bytes,8,opt,name=item_type,json=itemType,proto3" json:"item_type,omitempty"`
	ItemId           string                 `protobuf:"bytes,9,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	TmdbId           int32                  `protobuf:"varint,10,opt,name=tmdb_id,json=tmdbId,proto3" json:"tmdb_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DispatchRequest) Reset() {
	*x = DispatchRequest{}
	mi := &file_proto_automationv1_automation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchRequest) ProtoMessage() {}

func (x *DispatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_automationv1_automation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchRequest.ProtoReflect.Descriptor instead.
func (*DispatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_automationv1_automation_proto_rawDescGZIP(), []int{3}
}

func (x *DispatchRequest) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

func (x *DispatchRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DispatchRequest) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *DispatchRequest) GetDownloadProtocol() string {
	if x != nil {
		return x.DownloadProtocol
	}
	return ""
}

func (x *DispatchRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *DispatchRequest) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *DispatchRequest) GetIndexerName() string {
	if x != nil {
		return x.IndexerName
	}
	return ""
}

func (x *DispatchRequest) GetItemType() string {
	if x != nil {
		return x.ItemType
	}
	return ""
}

func (x *DispatchRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *DispatchRequest) GetTmdbId() int32 {
	if x != nil {
		return x.TmdbId
	}
	return 0
}

type DispatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DownloadId    string                 `protobuf:"bytes,1,opt,name=download_id,json=downloadId,proto3" json:"download_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchResponse) Reset() {
	*x = DispatchResponse{}
	mi := &file_proto_automationv1_automation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchResponse) ProtoMessage() {}

func (x *DispatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_automationv1_automation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchResponse.ProtoReflect.Descriptor instead.
func (*DispatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_automationv1_automation_proto_rawDescGZIP(), []int{4}
}

func (x *DispatchResponse) GetDownloadId() string {
	if x != nil {
		return x.DownloadId
	}
	return ""
}

func (x *DispatchResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type AddToQueueRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ItemType         string                 `protobuf:"bytes,1,opt,name=item_type,json=itemType,proto3" json:"item_type,omitempty"`
	ItemId           string                 `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	TmdbId           int32                  `protobuf:"varint,3,opt,name=tmdb_id,json=tmdbId,proto3" json:"tmdb_id,omitempty"`
	Title            string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Year             int32                  `protobuf:"varint,5,opt,name=year,proto3" json:"year,omitempty"`
	SeasonNumber     int32                  `protobuf:"varint,6,opt,name=season_number,json=seasonNumber,proto3" json:"season_number,omitempty"`
	EpisodeNumber    int32                  `protobuf:"varint,7,opt,name=episode_number,json=episodeNumber,proto3" json:"episode_number,omitempty"`
	QualityProfileId string                 `protobuf:"bytes,8,opt,name=quality_profile_id,json=qualityProfileId,proto3" json:"quality_profile_id,omitempty"`
	AbsoluteNumber   int32                  `protobuf:"varint,9,opt,name=absolute_number,json=absoluteNumber,proto3" json:"absolute_number,omitempty"` // anime absolute episode number
	SeriesType       string                 `protobuf:"bytes,10,opt,name=series_type,json=seriesType,proto3" json:"series_type,omitempty"`             // "standard", "daily", or "anime"
	SeriesId         string                 `protobuf:"bytes,11,opt,name=series_id,json=seriesId,proto3" json:"series_id,omitempty"`                   // library series id (for overrides / grouping)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AddToQueueRequest) Reset() {
	*x = AddToQueueRequest{}
	mi := &file_proto_automationv1_automation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToQueueRequest) ProtoMessage() {}

func (x *AddToQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_automationv1_automation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToQueueRequest.ProtoReflect.Descriptor instead.
func (*AddToQueueRequest) Descriptor() ([]byte, []int) {
	return file_proto_automationv1_automation_proto_rawDescGZIP(), []int{5}
}

func (x *AddToQueueRequest) GetItemType() string {
	if x != nil {
		return x.ItemType
	}
	return ""
}

func (x *AddToQueueRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *AddToQueueRequest) GetTmdbId() int32 {
	if x != nil {
		return x.TmdbId
	}
	return 0
}

func (x *AddToQueueRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AddToQueueRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *AddToQueueRequest) GetSeasonNumber() int32 {
	if x != nil {
		return x.SeasonNumber
	}
	return 0
}

func (x *AddToQueueRequest) GetEpisodeNumber() int32 {
	if x != nil {
		return x.EpisodeNumber
	}
	return 0
}

func (x *AddToQueueRequest) GetQualityProfileId() string {
	if x != nil {
		return x.QualityProfileId
	}
	return ""
}

func (x *AddToQueueRequest) GetAbsoluteNumber() int32 {
	if x != nil {
		return x.AbsoluteNumber
	}
	return 0
}

func (x *AddToQueueRequest) GetSeriesType() string {
	if x != nil {
		return x.SeriesType
	}
	return ""
}

func (x *AddToQueueRequest) GetSeriesId() string {
	if x != nil {
		return x.SeriesId
	}
	return ""
}

type AddToQueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueueId       string                 `protobuf:"bytes,1,opt,name=queue_id,json=queueId,proto3" json:"queue_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddToQueueResponse) Reset() {
	*x = AddToQueueResponse{}
	mi := &file_proto_automationv1_automation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToQueueResponse) ProtoMessage() {}

func (x *AddToQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_automationv1_automation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToQueueResponse.ProtoReflect.Descriptor instead.
func (*AddToQueueResponse) Descriptor() ([]byte, []int) {
	return file_proto_automationv1_automation_proto_rawDescGZIP(), []int{6}
}

func (x *AddToQueueResponse) GetQueueId() string {
	if x != nil {
		return x.QueueId
	}
	return ""
}

type GetQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Filter        string                 `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQueueRequest) Reset() {
	*x = GetQueueRequest{}
	mi := &file_proto_automationv1_automation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueueRequest) ProtoMessage() {}

func (x *GetQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_automationv1_automation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueueRequest.ProtoReflect.Descriptor instead.
func (*GetQueueRequest) Descriptor() ([]byte, []int) {
	return file_proto_automationv1_automation_proto_rawDescGZIP(), []int{7}
}

func (x *GetQueueRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetQueueRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetQueueRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

type GetQueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*QueueItem           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQueueResponse) Reset() {
	*x = GetQueueResponse{}
	mi := &file_proto_automationv1_automation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueueResponse) ProtoMessage() {}

func (x *GetQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_automationv1_automation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueueResponse.ProtoReflect.Descriptor instead.
func (*GetQueueResponse) Descriptor() ([]byte, []int) {
	return file_proto_automationv1_automation_proto_rawDescGZIP(), []int{8}
}

func (x *GetQueueResponse) GetItems() []*QueueItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetQueueResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetQueueResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetQueueResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type QueueItem struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ItemType         string                 `protobuf:"bytes,2,opt,name=item_type,json=itemType,proto3" json:"item_type,omitempty"`
	ItemId           string                 `protobuf:"bytes,3,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	TmdbId           int32                  `protobuf:"varint,4,opt,name=tmdb_id,json=tmdbId,proto3" json:"tmdb_id,omitempty"`
	Title            string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Year             int32                  `protobuf:"varint,6,opt,name=year,proto3" json:"year,omitempty"`
	SeasonNumber     int32                  `protobuf:"varint,7,opt,name=season_number,json=seasonNumber,proto3" json:"season_number,omitempty"`
	EpisodeNumber    int32                  `protobuf:"varint,8,opt,name=episode_number,json=episodeNumber,proto3" json:"episode_number,omitempty"`
	Monitored        bool                   `protobuf:"varint,9,opt,name=monitored,proto3" json:"monitored,omitempty"`
	Missing          bool                   `protobuf:"varint,10,opt,name=missing,proto3" json:"missing,omitempty"`
	LastSearched     string                 `protobuf:"bytes,11,opt,name=last_searched,json=lastSearched,proto3" json:"last_searched,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        string                 `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	QualityProfileId string                 `protobuf:"bytes,14,opt,name=quality_profile_id,json=qualityProfileId,proto3" json:"quality_profile_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *QueueItem) Reset() {
	*x = QueueItem{}
	mi := &file_proto_automationv1_automation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueItem) ProtoMessage() {}

func (x *QueueItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_automationv1_automation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueItem.ProtoReflect.Descriptor instead.
func (*QueueItem) Descriptor() ([]byte, []int) {
	return file_proto_automationv1_automation_proto_rawDescGZIP(), []int{9}
}

func (x *QueueItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *QueueItem) GetItemType() string {
	if x != nil {
		return x.ItemType
	}
	return ""
}

func (x *QueueItem) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *QueueItem) GetTmdbId() int32 {
	if x != nil {
		return x.TmdbId
	}
	return 0
}

func (x *QueueItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *QueueItem) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *QueueItem) GetSeasonNumber() int32 {
	if x != nil {
		return x.SeasonNumber
	}
	return 0
}

func (x *QueueItem) GetEpisodeNumber() int32 {
	if x != nil {
		return x.EpisodeNumber
	}
	return 0
}

func (x *QueueItem) GetMonitored() bool {
	if x != nil {
		return x.Monitored
	}
	return false
}

func (x *QueueItem) GetMissing() bool {
	if x != nil {
		return x.Missing
	}
	return false
}

func (x *QueueItem) GetLastSearched() string {
	if x != nil {
		return x.LastSearched
	}
	return ""
}

func (x *QueueItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *QueueItem) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *QueueItem) GetQualityProfileId() string {
	if x != nil {
		return x.QualityProfileId
	}
	return ""
}

type GetHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryRequest) Reset() {
	*x = GetHistoryRequest{}
	mi := &file_proto_automationv1_automation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryRequest) ProtoMessage() {}

func (x *GetHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_automationv1_automation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_automationv1_automation_proto_rawDescGZIP(), []int{10}
}

func (x *GetHistoryRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetHistoryRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*DownloadRecord      `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryResponse) Reset() {
	*x = GetHistoryResponse{}
	mi := &file_proto_automationv1_automation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryResponse) ProtoMessage() {}

func (x *GetHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_automationv1_automation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetHistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_automationv1_automation_proto_rawDescGZIP(), []int{11}
}

func (x *GetHistoryResponse) GetRecords() []*DownloadRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *GetHistoryResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetHistoryResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetHistoryResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type SearchNowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchNowRequest) Reset() {
	*x = SearchNowRequest{}
	mi := &file_proto_automationv1_automation_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchNowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchNowRequest) ProtoMessage() {}

func (x *SearchNowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_automationv1_automation_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchNowRequest.ProtoReflect.Descriptor instead.
func (*SearchNowRequest) Descriptor() ([]byte, []int) {
	return file_proto_automationv1_automation_proto_rawDescGZIP(), []int{12}
}

type SearchNowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Started       bool                   `protobuf:"varint,1,opt,name=started,proto3" json:"started,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchNowResponse) Reset() {
	*x = SearchNowResponse{}
	mi := &file_proto_automationv1_automation_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchNowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchNowResponse) ProtoMessage() {}

func (x *SearchNowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_automationv1_automation_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchNowResponse.ProtoReflect.Descriptor instead.
func (*SearchNowResponse) Descriptor() ([]byte, []int) {
	return file_proto_automationv1_automation_proto_rawDescGZIP(), []int{13}
}

func (x *SearchNowResponse) GetStarted() bool {
	if x != nil {
		return x.Started
	}
	return false
}

func (x *SearchNowResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DownloadRecord struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WantedItemId     string                 `protobuf:"bytes,2,opt,name=wanted_item_id,json=wantedItemId,proto3" json:"wanted_item_id,omitempty"`
	Guid             string                 `protobuf:"bytes,3,opt,name=guid,proto3" json:"guid,omitempty"`
	Title            string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Indexer          string                 `protobuf:"bytes,5,opt,name=indexer,proto3" json:"indexer,omitempty"`
	Size             int64                  `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
	Score            int32                  `protobuf:"varint,7,opt,name=score,proto3" json:"score,omitempty"`
	DownloadUrl      string                 `protobuf:"bytes,8,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	DownloadProtocol string                 `protobuf:"bytes,9,opt,name=download_protocol,json=downloadProtocol,proto3" json:"download_protocol,omitempty"`
	Status           string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	SentAt           string                 `protobuf:"bytes,11,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	CompletedAt      string                 `protobuf:"bytes,12,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	DownloadId       string                 `protobuf:"bytes,14,opt,name=download_id,json=downloadId,proto3" json:"download_id,omitempty"`
	StatusDetail     string                 `protobuf:"bytes,15,opt,name=status_detail,json=statusDetail,proto3" json:"status_detail,omitempty"` // operator-facing reason when status is failed/stalled/import_failed
	StatusLabel      string                 `protobuf:"bytes,16,opt,name=status_label,json=statusLabel,proto3" json:"status_label,omitempty"`    // human-readable label derived from status + status_detail
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DownloadRecord) Reset() {
	*x = DownloadRecord{}
	mi := &file_proto_automationv1_automation_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadRecord) ProtoMessage() {}

func (x *DownloadRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_automationv1_automation_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadRecord.ProtoReflect.Descriptor instead.
func (*DownloadRecord) Descriptor() ([]byte, []int) {
	return file_proto_automationv1_automation_proto_rawDescGZIP(), []int{14}
}

func (x *DownloadRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DownloadRecord) GetWantedItemId() string {
	if x != nil {
		return x.WantedItemId
	}
	return ""
}

func (x *DownloadRecord) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

func (x *DownloadRecord) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DownloadRecord) GetIndexer() string {
	if x != nil {
		return x.Indexer
	}
	return ""
}

func (x *DownloadRecord) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *DownloadRecord) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *DownloadRecord) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *DownloadRecord) GetDownloadProtocol() string {
	if x != nil {
		return x.DownloadProtocol
	}
	return ""
}

func (x *DownloadRecord) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DownloadRecord) GetSentAt() string {
	if x != nil {
		return x.SentAt
	}
	return ""
}

func (x *DownloadRecord) GetCompletedAt() string {
	if x != nil {
		return x.CompletedAt
	}
	return ""
}

func (x *DownloadRecord) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *DownloadRecord) GetDownloadId() string {
	if x != nil {
		return x.DownloadId
	}
	return ""
}

func (x *DownloadRecord) GetStatusDetail() string {
	if x != nil {
		return x.StatusDetail
	}
	return ""
}

func (x *DownloadRecord) GetStatusLabel() string {
	if x != nil {
		return x.StatusLabel
	}
	return ""
}

type RemoveFromQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueueId       string                 `protobuf:"bytes,1,opt,name=queue_id,json=queueId,proto3" json:"queue_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFromQueueRequest) Reset() {
	*x = RemoveFromQueueRequest{}
	mi := &file_proto_automationv1_automation_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFromQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFromQueueRequest) ProtoMessage() {}

func (x *RemoveFromQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_automationv1_automation_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFromQueueRequest.ProtoReflect.Descriptor instead.
func (*RemoveFromQueueRequest) Descriptor() ([]byte, []int) {
	return file_proto_automationv1_automation_proto_rawDescGZIP(), []int{15}
}

func (x *RemoveFromQueueRequest) GetQueueId() string {
	if x != nil {
		return x.QueueId
	}
	return ""
}

type RemoveFromQueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFromQueueResponse) Reset() {
	*x = RemoveFromQueueResponse{}
	mi := &file_proto_automationv1_automation_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFromQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFromQueueResponse) ProtoMessage() {}

func (x *RemoveFromQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_automationv1_automation_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFromQueueResponse.ProtoReflect.Descriptor instead.
func (*RemoveFromQueueResponse) Descriptor() ([]byte, []int) {
	return file_proto_automationv1_automation_proto_rawDescGZIP(), []int{16}
}

type ListBlocklistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	WantedItemId  string                 `protobuf:"bytes,3,opt,name=wanted_item_id,json=wantedItemId,proto3" json:"wanted_item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBlocklistRequest) Reset() {
	*x = ListBlocklistRequest{}
	mi := &file_proto_automationv1_automation_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBlocklistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlocklistRequest) ProtoMessage() {}

func (x *ListBlocklistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_automationv1_automation_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlocklistRequest.ProtoReflect.Descriptor instead.
func (*ListBlocklistRequest) Descriptor() ([]byte, []int) {
	return file_proto_automationv1_automation_proto_rawDescGZIP(), []int{17}
}

func (x *ListBlocklistRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListBlocklistRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListBlocklistRequest) GetWantedItemId() string {
	if x != nil {
		return x.WantedItemId
	}
	return ""
}

type BlocklistEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WantedItemId  string                 `protobuf:"bytes,1,opt,name=wanted_item_id,json=wantedItemId,proto3" json:"wanted_item_id,omitempty"`
	Guid          string                 `protobuf:"bytes,2,opt,name=guid,proto3" json:"guid,omitempty"`
	Loop          int32                  `protobuf:"varint,3,opt,name=loop,proto3" json:"loop,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Title         string                 `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlocklistEntry) Reset() {
	*x = BlocklistEntry{}
	mi := &file_proto_automationv1_automation_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlocklistEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlocklistEntry) ProtoMessage() {}

func (x *BlocklistEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_automationv1_automation_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlocklistEntry.ProtoReflect.Descriptor instead.
func (*BlocklistEntry) Descriptor() ([]byte, []int) {
	return file_proto_automationv1_automation_proto_rawDescGZIP(), []int{18}
}

func (x *BlocklistEntry) GetWantedItemId() string {
	if x != nil {
		return x.WantedItemId
	}
	return ""
}

func (x *BlocklistEntry) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

func (x *BlocklistEntry) GetLoop() int32 {
	if x != nil {
		return x.Loop
	}
	return 0
}

func (x *BlocklistEntry) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *BlocklistEntry) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *BlocklistEntry) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type ListBlocklistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*BlocklistEntry      `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBlocklistResponse) Reset() {
	*x = ListBlocklistResponse{}
	mi := &file_proto_automationv1_automation_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBlocklistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlocklistResponse) ProtoMessage() {}

func (x *ListBlocklistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_automationv1_automation_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlocklistResponse.ProtoReflect.Descriptor instead.
func (*ListBlocklistResponse) Descriptor() ([]byte, []int) {
	return file_proto_automationv1_automation_proto_rawDescGZIP(), []int{19}
}

func (x *ListBlocklistResponse) GetEntries() []*BlocklistEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ListBlocklistResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListBlocklistResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListBlocklistResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ClearBlocklistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WantedItemId  string                 `protobuf:"bytes,1,opt,name=wanted_item_id,json=wantedItemId,proto3" json:"wanted_item_id,omitempty"` // optional: clear one item's entries
	Guid          string                 `protobuf:"bytes,2,opt,name=guid,proto3" json:"guid,omitempty"`                                       // optional with wanted_item_id
	ClearAll      bool                   `protobuf:"varint,3,opt,name=clear_all,json=clearAll,proto3" json:"clear_all,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearBlocklistRequest) Reset() {
	*x = ClearBlocklistRequest{}
	mi := &file_proto_automationv1_automation_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearBlocklistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearBlocklistRequest) ProtoMessage() {}

func (x *ClearBlocklistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_automationv1_automation_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearBlocklistRequest.ProtoReflect.Descriptor instead.
func (*ClearBlocklistRequest) Descriptor() ([]byte, []int) {
	return file_proto_automationv1_automation_proto_rawDescGZIP(), []int{20}
}

func (x *ClearBlocklistRequest) GetWantedItemId() string {
	if x != nil {
		return x.WantedItemId
	}
	return ""
}

func (x *ClearBlocklistRequest) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

func (x *ClearBlocklistRequest) GetClearAll() bool {
	if x != nil {
		return x.ClearAll
	}
	return false
}

type ClearBlocklistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Removed       int32                  `protobuf:"varint,1,opt,name=removed,proto3" json:"removed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearBlocklistResponse) Reset() {
	*x = ClearBlocklistResponse{}
	mi := &file_proto_automationv1_automation_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearBlocklistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearBlocklistResponse) ProtoMessage() {}

func (x *ClearBlocklistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_automationv1_automation_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearBlocklistResponse.ProtoReflect.Descriptor instead.
func (*ClearBlocklistResponse) Descriptor() ([]byte, []int) {
	return file_proto_automationv1_automation_proto_rawDescGZIP(), []int{21}
}

func (x *ClearBlocklistResponse) GetRemoved() int32 {
	if x != nil {
		return x.Removed
	}
	return 0
}

type ListDelayProfilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDelayProfilesRequest) Reset() {
	*x = ListDelayProfilesRequest{}
	mi := &file_proto_automationv1_automation_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDelayProfilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDelayProfilesRequest) ProtoMessage() {}

func (x *ListDelayProfilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_automationv1_automation_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDelayProfilesRequest.ProtoReflect.Descriptor instead.
func (*ListDelayProfilesRequest) Descriptor() ([]byte, []int) {
	return file_proto_automationv1_automation_proto_rawDescGZIP(), []int{22}
}

type DelayProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      string                 `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	WaitMinutes   int32                  `protobuf:"varint,2,opt,name=wait_minutes,json=waitMinutes,proto3" json:"wait_minutes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelayProfile) Reset() {
	*x = DelayProfile{}
	mi := &file_proto_automationv1_automation_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelayProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelayProfile) ProtoMessage() {}

func (x *DelayProfile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_automationv1_automation_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelayProfile.ProtoReflect.Descriptor instead.
func (*DelayProfile) Descriptor() ([]byte, []int) {
	return file_proto_automationv1_automation_proto_rawDescGZIP(), []int{23}
}

func (x *DelayProfile) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *DelayProfile) GetWaitMinutes() int32 {
	if x != nil {
		return x.WaitMinutes
	}
	return 0
}

type ListDelayProfilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profiles      []*DelayProfile        `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDelayProfilesResponse) Reset() {
	*x = ListDelayProfilesResponse{}
	mi := &file_proto_automationv1_automation_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDelayProfilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDelayProfilesResponse) ProtoMessage() {}

func (x *ListDelayProfilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_automationv1_automation_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDelayProfilesResponse.ProtoReflect.Descriptor instead.
func (*ListDelayProfilesResponse) Descriptor() ([]byte, []int) {
	return file_proto_automationv1_automation_proto_rawDescGZIP(), []int{24}
}

func (x *ListDelayProfilesResponse) GetProfiles() []*DelayProfile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

type UpsertDelayProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      string                 `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	WaitMinutes   int32                  `protobuf:"varint,2,opt,name=wait_minutes,json=waitMinutes,proto3" json:"wait_minutes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertDelayProfileRequest) Reset() {
	*x = UpsertDelayProfileRequest{}
	mi := &file_proto_automationv1_automation_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertDelayProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertDelayProfileRequest) ProtoMessage() {}

func (x *UpsertDelayProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_automationv1_automation_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertDelayProfileRequest.ProtoReflect.Descriptor instead.
func (*UpsertDelayProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_automationv1_automation_proto_rawDescGZIP(), []int{25}
}

func (x *UpsertDelayProfileRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *UpsertDelayProfileRequest) GetWaitMinutes() int32 {
	if x != nil {
		return x.WaitMinutes
	}
	return 0
}

type UpsertDelayProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *DelayProfile          `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertDelayProfileResponse) Reset() {
	*x = UpsertDelayProfileResponse{}
	mi := &file_proto_automationv1_automation_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertDelayProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertDelayProfileResponse) ProtoMessage() {}

func (x *UpsertDelayProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_automationv1_automation_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertDelayProfileResponse.ProtoReflect.Descriptor instead.
func (*UpsertDelayProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_automationv1_automation_proto_rawDescGZIP(), []int{26}
}

func (x *UpsertDelayProfileResponse) GetProfile() *DelayProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type ListCutoffUnmetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCutoffUnmetRequest) Reset() {
	*x = ListCutoffUnmetRequest{}
	mi := &file_proto_automationv1_automation_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCutoffUnmetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCutoffUnmetRequest) ProtoMessage() {}

func (x *ListCutoffUnmetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_automationv1_automation_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCutoffUnmetRequest.ProtoReflect.Descriptor instead.
func (*ListCutoffUnmetRequest) Descriptor() ([]byte, []int) {
	return file_proto_automationv1_automation_proto_rawDescGZIP(), []int{27}
}

func (x *ListCutoffUnmetRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListCutoffUnmetRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type CutoffItem struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	QueueId          string                 `protobuf:"bytes,1,opt,name=queue_id,json=queueId,proto3" json:"queue_id,omitempty"`
	ItemType         string                 `protobuf:"bytes,2,opt,name=item_type,json=itemType,proto3" json:"item_type,omitempty"`
	ItemId           string                 `protobuf:"bytes,3,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Title            string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Year             int32                  `protobuf:"varint,5,opt,name=year,proto3" json:"year,omitempty"`
	CurrentScore     int32                  `protobuf:"varint,6,opt,name=current_score,json=currentScore,proto3" json:"current_score,omitempty"`
	CutoffScore      int32                  `protobuf:"varint,7,opt,name=cutoff_score,json=cutoffScore,proto3" json:"cutoff_score,omitempty"`
	QualityProfileId string                 `protobuf:"bytes,8,opt,name=quality_profile_id,json=qualityProfileId,proto3" json:"quality_profile_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CutoffItem) Reset() {
	*x = CutoffItem{}
	mi := &file_proto_automationv1_automation_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CutoffItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CutoffItem) ProtoMessage() {}

func (x *CutoffItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_automationv1_automation_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CutoffItem.ProtoReflect.Descriptor instead.
func (*CutoffItem) Descriptor() ([]byte, []int) {
	return file_proto_automationv1_automation_proto_rawDescGZIP(), []int{28}
}

func (x *CutoffItem) GetQueueId() string {
	if x != nil {
		return x.QueueId
	}
	return ""
}

func (x *CutoffItem) GetItemType() string {
	if x != nil {
		return x.ItemType
	}
	return ""
}

func (x *CutoffItem) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *CutoffItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CutoffItem) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *CutoffItem) GetCurrentScore() int32 {
	if x != nil {
		return x.CurrentScore
	}
	return 0
}

func (x *CutoffItem) GetCutoffScore() int32 {
	if x != nil {
		return x.CutoffScore
	}
	return 0
}

func (x *CutoffItem) GetQualityProfileId() string {
	if x != nil {
		return x.QualityProfileId
	}
	return ""
}

type ListCutoffUnmetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*CutoffItem          `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCutoffUnmetResponse) Reset() {
	*x = ListCutoffUnmetResponse{}
	mi := &file_proto_automationv1_automation_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCutoffUnmetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCutoffUnmetResponse) ProtoMessage() {}

func (x *ListCutoffUnmetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_automationv1_automation_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCutoffUnmetResponse.ProtoReflect.Descriptor instead.
func (*ListCutoffUnmetResponse) Descriptor() ([]byte, []int) {
	return file_proto_automationv1_automation_proto_rawDescGZIP(), []int{29}
}

func (x *ListCutoffUnmetResponse) GetItems() []*CutoffItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListCutoffUnmetResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListCutoffUnmetResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListCutoffUnmetResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type BlocklistReleaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WantedItemId  string                 `protobuf:"bytes,1,opt,name=wanted_item_id,json=wantedItemId,proto3" json:"wanted_item_id,omitempty"`
	Guid          string                 `protobuf:"bytes,2,opt,name=guid,proto3" json:"guid,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Loop          int32                  `protobuf:"varint,4,opt,name=loop,proto3" json:"loop,omitempty"` // optional; defaults to 1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlocklistReleaseRequest) Reset() {
	*x = BlocklistReleaseRequest{}
	mi := &file_proto_automationv1_automation_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlocklistReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlocklistReleaseRequest) ProtoMessage() {}

func (x *BlocklistReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_automationv1_automation_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlocklistReleaseRequest.ProtoReflect.Descriptor instead.
func (*BlocklistReleaseRequest) Descriptor() ([]byte, []int) {
	return file_proto_automationv1_automation_proto_rawDescGZIP(), []int{30}
}

func (x *BlocklistReleaseRequest) GetWantedItemId() string {
	if x != nil {
		return x.WantedItemId
	}
	return ""
}

func (x *BlocklistReleaseRequest) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

func (x *BlocklistReleaseRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *BlocklistReleaseRequest) GetLoop() int32 {
	if x != nil {
		return x.Loop
	}
	return 0
}

type BlocklistReleaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlocklistReleaseResponse) Reset() {
	*x = BlocklistReleaseResponse{}
	mi := &file_proto_automationv1_automation_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlocklistReleaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlocklistReleaseResponse) ProtoMessage() {}

func (x *BlocklistReleaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_automationv1_automation_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlocklistReleaseResponse.ProtoReflect.Descriptor instead.
func (*BlocklistReleaseResponse) Descriptor() ([]byte, []int) {
	return file_proto_automationv1_automation_proto_rawDescGZIP(), []int{31}
}

func (x *BlocklistReleaseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RetryImportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HistoryId     string                 `protobuf:"bytes,1,opt,name=history_id,json=historyId,proto3" json:"history_id,omitempty"` // optional; empty = retry all import_failed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryImportRequest) Reset() {
	*x = RetryImportRequest{}
	mi := &file_proto_automationv1_automation_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryImportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryImportRequest) ProtoMessage() {}

func (x *RetryImportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_automationv1_automation_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryImportRequest.ProtoReflect.Descriptor instead.
func (*RetryImportRequest) Descriptor() ([]byte, []int) {
	return file_proto_automationv1_automation_proto_rawDescGZIP(), []int{32}
}

func (x *RetryImportRequest) GetHistoryId() string {
	if x != nil {
		return x.HistoryId
	}
	return ""
}

type RetryImportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attempted     int32                  `protobuf:"varint,1,opt,name=attempted,proto3" json:"attempted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryImportResponse) Reset() {
	*x = RetryImportResponse{}
	mi := &file_proto_automationv1_automation_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryImportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryImportResponse) ProtoMessage() {}

func (x *RetryImportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_automationv1_automation_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryImportResponse.ProtoReflect.Descriptor instead.
func (*RetryImportResponse) Descriptor() ([]byte, []int) {
	return file_proto_automationv1_automation_proto_rawDescGZIP(), []int{33}
}

func (x *RetryImportResponse) GetAttempted() int32 {
	if x != nil {
		return x.Attempted
	}
	return 0
}

func (x *RetryImportResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_automationv1_automation_proto protoreflect.FileDescriptor

const file_proto_automationv1_automation_proto_rawDesc = "" +
	"\n" +
	"#proto/automationv1/automation.proto\x12\x15muxcore.automation.v1\"\xa6\x02\n" +
	"\x11SearchItemRequest\x12\x1b\n" +
	"\titem_type\x18\x01 \x01(\tR\bitemType\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x17\n" +
	"\atmdb_id\x18\x03 \x01(\x05R\x06tmdbId\x12\x12\n" +
	"\x04year\x18\x04 \x01(\x05R\x04year\x12\x16\n" +
	"\x06season\x18\x05 \x01(\x05R\x06season\x12\x18\n" +
	"\aepisode\x18\x06 \x01(\x05R\aepisode\x12\x14\n" +
	"\x05limit\x18\a \x01(\x05R\x05limit\x12,\n" +
	"\x12quality_profile_id\x18\b \x01(\tR\x10qualityProfileId\x12\x1a\n" +
	"\babsolute\x18\t \x01(\x05R\babsolute\x12\x1f\n" +
	"\vseries_type\x18\n" +
	" \x01(\tR\n" +
	"seriesType\"S\n" +
	"\x12SearchItemResponse\x12=\n" +
	"\amatches\x18\x01 \x03(\v2#.muxcore.automation.v1.ReleaseMatchR\amatches\"\xdf\x02\n" +
	"\fReleaseMatch\x12\x12\n" +
	"\x04guid\x18\x01 \x01(\tR\x04guid\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x18\n" +
	"\aseeders\x18\x04 \x01(\x05R\aseeders\x12\x14\n" +
	"\x05peers\x18\x05 \x01(\x05R\x05peers\x12!\n" +
	"\findexer_name\x18\x06 \x01(\tR\vindexerName\x12!\n" +
	"\fdownload_url\x18\a \x01(\tR\vdownloadUrl\x12\x19\n" +
	"\binfo_url\x18\b \x01(\tR\ainfoUrl\x12+\n" +
	"\x11download_protocol\x18\t \x01(\tR\x10downloadProtocol\x12\x14\n" +
	"\x05score\x18\n" +
	" \x01(\x05R\x05score\x12\x1a\n" +
	"\bcategory\x18\v \x01(\tR\bcategory\x12!\n" +
	"\fsub_category\x18\f \x01(\tR\vsubCategory\"\xa7\x02\n" +
	"\x0fDispatchRequest\x12\x12\n" +
	"\x04guid\x18\x01 \x01(\tR\x04guid\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12!\n" +
	"\fdownload_url\x18\x03 \x01(\tR\vdownloadUrl\x12+\n" +
	"\x11download_protocol\x18\x04 \x01(\tR\x10downloadProtocol\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x03R\x04size\x12\x14\n" +
	"\x05score\x18\x06 \x01(\x05R\x05score\x12!\n" +
	"\findexer_name\x18\a \x01(\tR\vindexerName\x12\x1b\n" +
	"\titem_type\x18\b \x01(\tR\bitemType\x12\x17\n" +
	"\aitem_id\x18\t \x01(\tR\x06itemId\x12\x17\n" +
	"\atmdb_id\x18\n" +
	" \x01(\x05R\x06tmdbId\"K\n" +
	"\x10DispatchResponse\x12\x1f\n" +
	"\vdownload_id\x18\x01 \x01(\tR\n" +
	"downloadId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\xed\x02\n" +
	"\x11AddToQueueRequest\x12\x1b\n" +
	"\titem_type\x18\x01 \x01(\tR\bitemType\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\tR\x06itemId\x12\x17\n" +
	"\atmdb_id\x18\x03 \x01(\x05R\x06tmdbId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x12\n" +
	"\x04year\x18\x05 \x01(\x05R\x04year\x12#\n" +
	"\rseason_number\x18\x06 \x01(\x05R\fseasonNumber\x12%\n" +
	"\x0eepisode_number\x18\a \x01(\x05R\repisodeNumber\x12,\n" +
	"\x12quality_profile_id\x18\b \x01(\tR\x10qualityProfileId\x12'\n" +
	"\x0fabsolute_number\x18\t \x01(\x05R\x0eabsoluteNumber\x12\x1f\n" +
	"\vseries_type\x18\n" +
	" \x01(\tR\n" +
	"seriesType\x12\x1b\n" +
	"\tseries_id\x18\v \x01(\tR\bseriesId\"/\n" +
	"\x12AddToQueueResponse\x12\x19\n" +
	"\bqueue_id\x18\x01 \x01(\tR\aqueueId\"Z\n" +
	"\x0fGetQueueRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06filter\x18\x03 \x01(\tR\x06filter\"\x91\x01\n" +
	"\x10GetQueueResponse\x126\n" +
	"\x05items\x18\x01 \x03(\v2 .muxcore.automation.v1.QueueItemR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\xa9\x03\n" +
	"\tQueueItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\titem_type\x18\x02 \x01(\tR\bitemType\x12\x17\n" +
	"\aitem_id\x18\x03 \x01(\tR\x06itemId\x12\x17\n" +
	"\atmdb_id\x18\x04 \x01(\x05R\x06tmdbId\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x12\n" +
	"\x04year\x18\x06 \x01(\x05R\x04year\x12#\n" +
	"\rseason_number\x18\a \x01(\x05R\fseasonNumber\x12%\n" +
	"\x0eepisode_number\x18\b \x01(\x05R\repisodeNumber\x12\x1c\n" +
	"\tmonitored\x18\t \x01(\bR\tmonitored\x12\x18\n" +
	"\amissing\x18\n" +
	" \x01(\bR\amissing\x12#\n" +
	"\rlast_searched\x18\v \x01(\tR\flastSearched\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\r \x01(\tR\tupdatedAt\x12,\n" +
	"\x12quality_profile_id\x18\x0e \x01(\tR\x10qualityProfileId\"D\n" +
	"\x11GetHistoryRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"\x9c\x01\n" +
	"\x12GetHistoryResponse\x12?\n" +
	"\arecords\x18\x01 \x03(\v2%.muxcore.automation.v1.DownloadRecordR\arecords\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\x12\n" +
	"\x10SearchNowRequest\"G\n" +
	"\x11SearchNowResponse\x12\x18\n" +
	"\astarted\x18\x01 \x01(\bR\astarted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xe0\x03\n" +
	"\x0eDownloadRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12$\n" +
	"\x0ewanted_item_id\x18\x02 \x01(\tR\fwantedItemId\x12\x12\n" +
	"\x04guid\x18\x03 \x01(\tR\x04guid\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x18\n" +
	"\aindexer\x18\x05 \x01(\tR\aindexer\x12\x12\n" +
	"\x04size\x18\x06 \x01(\x03R\x04size\x12\x14\n" +
	"\x05score\x18\a \x01(\x05R\x05score\x12!\n" +
	"\fdownload_url\x18\b \x01(\tR\vdownloadUrl\x12+\n" +
	"\x11download_protocol\x18\t \x01(\tR\x10downloadProtocol\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x12\x17\n" +
	"\asent_at\x18\v \x01(\tR\x06sentAt\x12!\n" +
	"\fcompleted_at\x18\f \x01(\tR\vcompletedAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\r \x01(\tR\tcreatedAt\x12\x1f\n" +
	"\vdownload_id\x18\x0e \x01(\tR\n" +
	"downloadId\x12#\n" +
	"\rstatus_detail\x18\x0f \x01(\tR\fstatusDetail\x12!\n" +
	"\fstatus_label\x18\x10 \x01(\tR\vstatusLabel\"3\n" +
	"\x16RemoveFromQueueRequest\x12\x19\n" +
	"\bqueue_id\x18\x01 \x01(\tR\aqueueId\"\x19\n" +
	"\x17RemoveFromQueueResponse\"m\n" +
	"\x14ListBlocklistRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12$\n" +
	"\x0ewanted_item_id\x18\x03 \x01(\tR\fwantedItemId\"\xab\x01\n" +
	"\x0eBlocklistEntry\x12$\n" +
	"\x0ewanted_item_id\x18\x01 \x01(\tR\fwantedItemId\x12\x12\n" +
	"\x04guid\x18\x02 \x01(\tR\x04guid\x12\x12\n" +
	"\x04loop\x18\x03 \x01(\x05R\x04loop\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\"\x9f\x01\n" +
	"\x15ListBlocklistResponse\x12?\n" +
	"\aentries\x18\x01 \x03(\v2%.muxcore.automation.v1.BlocklistEntryR\aentries\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"n\n" +
	"\x15ClearBlocklistRequest\x12$\n" +
	"\x0ewanted_item_id\x18\x01 \x01(\tR\fwantedItemId\x12\x12\n" +
	"\x04guid\x18\x02 \x01(\tR\x04guid\x12\x1b\n" +
	"\tclear_all\x18\x03 \x01(\bR\bclearAll\"2\n" +
	"\x16ClearBlocklistResponse\x12\x18\n" +
	"\aremoved\x18\x01 \x01(\x05R\aremoved\"\x1a\n" +
	"\x18ListDelayProfilesRequest\"M\n" +
	"\fDelayProfile\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12!\n" +
	"\fwait_minutes\x18\x02 \x01(\x05R\vwaitMinutes\"\\\n" +
	"\x19ListDelayProfilesResponse\x12?\n" +
	"\bprofiles\x18\x01 \x03(\v2#.muxcore.automation.v1.DelayProfileR\bprofiles\"Z\n" +
	"\x19UpsertDelayProfileRequest\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12!\n" +
	"\fwait_minutes\x18\x02 \x01(\x05R\vwaitMinutes\"[\n" +
	"\x1aUpsertDelayProfileResponse\x12=\n" +
	"\aprofile\x18\x01 \x01(\v2#.muxcore.automation.v1.DelayProfileR\aprofile\"I\n" +
	"\x16ListCutoffUnmetRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"\xfd\x01\n" +
	"\n" +
	"CutoffItem\x12\x19\n" +
	"\bqueue_id\x18\x01 \x01(\tR\aqueueId\x12\x1b\n" +
	"\titem_type\x18\x02 \x01(\tR\bitemType\x12\x17\n" +
	"\aitem_id\x18\x03 \x01(\tR\x06itemId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x12\n" +
	"\x04year\x18\x05 \x01(\x05R\x04year\x12#\n" +
	"\rcurrent_score\x18\x06 \x01(\x05R\fcurrentScore\x12!\n" +
	"\fcutoff_score\x18\a \x01(\x05R\vcutoffScore\x12,\n" +
	"\x12quality_profile_id\x18\b \x01(\tR\x10qualityProfileId\"\x99\x01\n" +
	"\x17ListCutoffUnmetResponse\x127\n" +
	"\x05items\x18\x01 \x03(\v2!.muxcore.automation.v1.CutoffItemR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\x7f\n" +
	"\x17BlocklistReleaseRequest\x12$\n" +
	"\x0ewanted_item_id\x18\x01 \x01(\tR\fwantedItemId\x12\x12\n" +
	"\x04guid\x18\x02 \x01(\tR\x04guid\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x12\n" +
	"\x04loop\x18\x04 \x01(\x05R\x04loop\"4\n" +
	"\x18BlocklistReleaseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"3\n" +
	"\x12RetryImportRequest\x12\x1d\n" +
	"\n" +
	"history_id\x18\x01 \x01(\tR\thistoryId\"M\n" +
	"\x13RetryImportResponse\x12\x1c\n" +
	"\tattempted\x18\x01 \x01(\x05R\tattempted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xe3\v\n" +
	"\x11AutomationService\x12a\n" +
	"\n" +
	"SearchItem\x12(.muxcore.automation.v1.SearchItemRequest\x1a).muxcore.automation.v1.SearchItemResponse\x12[\n" +
	"\bDispatch\x12&.muxcore.automation.v1.DispatchRequest\x1a'.muxcore.automation.v1.DispatchResponse\x12a\n" +
	"\n" +
	"AddToQueue\x12(.muxcore.automation.v1.AddToQueueRequest\x1a).muxcore.automation.v1.AddToQueueResponse\x12[\n" +
	"\bGetQueue\x12&.muxcore.automation.v1.GetQueueRequest\x1a'.muxcore.automation.v1.GetQueueResponse\x12p\n" +
	"\x0fRemoveFromQueue\x12-.muxcore.automation.v1.RemoveFromQueueRequest\x1a..muxcore.automation.v1.RemoveFromQueueResponse\x12a\n" +
	"\n" +
	"GetHistory\x12(.muxcore.automation.v1.GetHistoryRequest\x1a).muxcore.automation.v1.GetHistoryResponse\x12^\n" +
	"\tSearchNow\x12'.muxcore.automation.v1.SearchNowRequest\x1a(.muxcore.automation.v1.SearchNowResponse\x12j\n" +
	"\rListBlocklist\x12+.muxcore.automation.v1.ListBlocklistRequest\x1a,.muxcore.automation.v1.ListBlocklistResponse\x12m\n" +
	"\x0eClearBlocklist\x12,.muxcore.automation.v1.ClearBlocklistRequest\x1a-.muxcore.automation.v1.ClearBlocklistResponse\x12s\n" +
	"\x10BlocklistRelease\x12..muxcore.automation.v1.BlocklistReleaseRequest\x1a/.muxcore.automation.v1.BlocklistReleaseResponse\x12d\n" +
	"\vRetryImport\x12).muxcore.automation.v1.RetryImportRequest\x1a*.muxcore.automation.v1.RetryImportResponse\x12v\n" +
	"\x11ListDelayProfiles\x12/.muxcore.automation.v1.ListDelayProfilesRequest\x1a0.muxcore.automation.v1.ListDelayProfilesResponse\x12y\n" +
	"\x12UpsertDelayProfile\x120.muxcore.automation.v1.UpsertDelayProfileRequest\x1a1.muxcore.automation.v1.UpsertDelayProfileResponse\x12p\n" +
	"\x0fListCutoffUnmet\x12-.muxcore.automation.v1.ListCutoffUnmetRequest\x1a..muxcore.automation.v1.ListCutoffUnmetResponseBKZIgithub.com/Muxcore-Media/media-automation/proto/automationv1;automationv1b\x06proto3"

var (
	file_proto_automationv1_automation_proto_rawDescOnce sync.Once
	file_proto_automationv1_automation_proto_rawDescData []byte
)

func file_proto_automationv1_automation_proto_rawDescGZIP() []byte {
	file_proto_automationv1_automation_proto_rawDescOnce.Do(func() {
		file_proto_automationv1_automation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_automationv1_automation_proto_rawDesc), len(file_proto_automationv1_automation_proto_rawDesc)))
	})
	return file_proto_automationv1_automation_proto_rawDescData
}

var file_proto_automationv1_automation_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_proto_automationv1_automation_proto_goTypes = []any{
	(*SearchItemRequest)(nil),          // 0: muxcore.automation.v1.SearchItemRequest
	(*SearchItemResponse)(nil),         // 1: muxcore.automation.v1.SearchItemResponse
	(*ReleaseMatch)(nil),               // 2: muxcore.automation.v1.ReleaseMatch
	(*DispatchRequest)(nil),            // 3: muxcore.automation.v1.DispatchRequest
	(*DispatchResponse)(nil),           // 4: muxcore.automation.v1.DispatchResponse
	(*AddToQueueRequest)(nil),          // 5: muxcore.automation.v1.AddToQueueRequest
	(*AddToQueueResponse)(nil),         // 6: muxcore.automation.v1.AddToQueueResponse
	(*GetQueueRequest)(nil),            // 7: muxcore.automation.v1.GetQueueRequest
	(*GetQueueResponse)(nil),           // 8: muxcore.automation.v1.GetQueueResponse
	(*QueueItem)(nil),                  // 9: muxcore.automation.v1.QueueItem
	(*GetHistoryRequest)(nil),          // 10: muxcore.automation.v1.GetHistoryRequest
	(*GetHistoryResponse)(nil),         // 11: muxcore.automation.v1.GetHistoryResponse
	(*SearchNowRequest)(nil),           // 12: muxcore.automation.v1.SearchNowRequest
	(*SearchNowResponse)(nil),          // 13: muxcore.automation.v1.SearchNowResponse
	(*DownloadRecord)(nil),             // 14: muxcore.automation.v1.DownloadRecord
	(*RemoveFromQueueRequest)(nil),     // 15: muxcore.automation.v1.RemoveFromQueueRequest
	(*RemoveFromQueueResponse)(nil),    // 16: muxcore.automation.v1.RemoveFromQueueResponse
	(*ListBlocklistRequest)(nil),       // 17: muxcore.automation.v1.ListBlocklistRequest
	(*BlocklistEntry)(nil),             // 18: muxcore.automation.v1.BlocklistEntry
	(*ListBlocklistResponse)(nil),      // 19: muxcore.automation.v1.ListBlocklistResponse
	(*ClearBlocklistRequest)(nil),      // 20: muxcore.automation.v1.ClearBlocklistRequest
	(*ClearBlocklistResponse)(nil),     // 21: muxcore.automation.v1.ClearBlocklistResponse
	(*ListDelayProfilesRequest)(nil),   // 22: muxcore.automation.v1.ListDelayProfilesRequest
	(*DelayProfile)(nil),               // 23: muxcore.automation.v1.DelayProfile
	(*ListDelayProfilesResponse)(nil),  // 24: muxcore.automation.v1.ListDelayProfilesResponse
	(*UpsertDelayProfileRequest)(nil),  // 25: muxcore.automation.v1.UpsertDelayProfileRequest
	(*UpsertDelayProfileResponse)(nil), // 26: muxcore.automation.v1.UpsertDelayProfileResponse
	(*ListCutoffUnmetRequest)(nil),     // 27: muxcore.automation.v1.ListCutoffUnmetRequest
	(*CutoffItem)(nil),                 // 28: muxcore.automation.v1.CutoffItem
	(*ListCutoffUnmetResponse)(nil),    // 29: muxcore.automation.v1.ListCutoffUnmetResponse
	(*BlocklistReleaseRequest)(nil),    // 30: muxcore.automation.v1.BlocklistReleaseRequest
	(*BlocklistReleaseResponse)(nil),   // 31: muxcore.automation.v1.BlocklistReleaseResponse
	(*RetryImportRequest)(nil),         // 32: muxcore.automation.v1.RetryImportRequest
	(*RetryImportResponse)(nil),        // 33: muxcore.automation.v1.RetryImportResponse
}
var file_proto_automationv1_automation_proto_depIdxs = []int32{
	2,  // 0: muxcore.automation.v1.SearchItemResponse.matches:type_name -> muxcore.automation.v1.ReleaseMatch
	9,  // 1: muxcore.automation.v1.GetQueueResponse.items:type_name -> muxcore.automation.v1.QueueItem
	14, // 2: muxcore.automation.v1.GetHistoryResponse.records:type_name -> muxcore.automation.v1.DownloadRecord
	18, // 3: muxcore.automation.v1.ListBlocklistResponse.entries:type_name -> muxcore.automation.v1.BlocklistEntry
	23, // 4: muxcore.automation.v1.ListDelayProfilesResponse.profiles:type_name -> muxcore.automation.v1.DelayProfile
	23, // 5: muxcore.automation.v1.UpsertDelayProfileResponse.profile:type_name -> muxcore.automation.v1.DelayProfile
	28, // 6: muxcore.automation.v1.ListCutoffUnmetResponse.items:type_name -> muxcore.automation.v1.CutoffItem
	0,  // 7: muxcore.automation.v1.AutomationService.SearchItem:input_type -> muxcore.automation.v1.SearchItemRequest
	3,  // 8: muxcore.automation.v1.AutomationService.Dispatch:input_type -> muxcore.automation.v1.DispatchRequest
	5,  // 9: muxcore.automation.v1.AutomationService.AddToQueue:input_type -> muxcore.automation.v1.AddToQueueRequest
	7,  // 10: muxcore.automation.v1.AutomationService.GetQueue:input_type -> muxcore.automation.v1.GetQueueRequest
	15, // 11: muxcore.automation.v1.AutomationService.RemoveFromQueue:input_type -> muxcore.automation.v1.RemoveFromQueueRequest
	10, // 12: muxcore.automation.v1.AutomationService.GetHistory:input_type -> muxcore.automation.v1.GetHistoryRequest
	12, // 13: muxcore.automation.v1.AutomationService.SearchNow:input_type -> muxcore.automation.v1.SearchNowRequest
	17, // 14: muxcore.automation.v1.AutomationService.ListBlocklist:input_type -> muxcore.automation.v1.ListBlocklistRequest
	20, // 15: muxcore.automation.v1.AutomationService.ClearBlocklist:input_type -> muxcore.automation.v1.ClearBlocklistRequest
	30, // 16: muxcore.automation.v1.AutomationService.BlocklistRelease:input_type -> muxcore.automation.v1.BlocklistReleaseRequest
	32, // 17: muxcore.automation.v1.AutomationService.RetryImport:input_type -> muxcore.automation.v1.RetryImportRequest
	22, // 18: muxcore.automation.v1.AutomationService.ListDelayProfiles:input_type -> muxcore.automation.v1.ListDelayProfilesRequest
	25, // 19: muxcore.automation.v1.AutomationService.UpsertDelayProfile:input_type -> muxcore.automation.v1.UpsertDelayProfileRequest
	27, // 20: muxcore.automation.v1.AutomationService.ListCutoffUnmet:input_type -> muxcore.automation.v1.ListCutoffUnmetRequest
	1,  // 21: muxcore.automation.v1.AutomationService.SearchItem:output_type -> muxcore.automation.v1.SearchItemResponse
	4,  // 22: muxcore.automation.v1.AutomationService.Dispatch:output_type -> muxcore.automation.v1.DispatchResponse
	6,  // 23: muxcore.automation.v1.AutomationService.AddToQueue:output_type -> muxcore.automation.v1.AddToQueueResponse
	8,  // 24: muxcore.automation.v1.AutomationService.GetQueue:output_type -> muxcore.automation.v1.GetQueueResponse
	16, // 25: muxcore.automation.v1.AutomationService.RemoveFromQueue:output_type -> muxcore.automation.v1.RemoveFromQueueResponse
	11, // 26: muxcore.automation.v1.AutomationService.GetHistory:output_type -> muxcore.automation.v1.GetHistoryResponse
	13, // 27: muxcore.automation.v1.AutomationService.SearchNow:output_type -> muxcore.automation.v1.SearchNowResponse
	19, // 28: muxcore.automation.v1.AutomationService.ListBlocklist:output_type -> muxcore.automation.v1.ListBlocklistResponse
	21, // 29: muxcore.automation.v1.AutomationService.ClearBlocklist:output_type -> muxcore.automation.v1.ClearBlocklistResponse
	31, // 30: muxcore.automation.v1.AutomationService.BlocklistRelease:output_type -> muxcore.automation.v1.BlocklistReleaseResponse
	33, // 31: muxcore.automation.v1.AutomationService.RetryImport:output_type -> muxcore.automation.v1.RetryImportResponse
	24, // 32: muxcore.automation.v1.AutomationService.ListDelayProfiles:output_type -> muxcore.automation.v1.ListDelayProfilesResponse
	26, // 33: muxcore.automation.v1.AutomationService.UpsertDelayProfile:output_type -> muxcore.automation.v1.UpsertDelayProfileResponse
	29, // 34: muxcore.automation.v1.AutomationService.ListCutoffUnmet:output_type -> muxcore.automation.v1.ListCutoffUnmetResponse
	21, // [21:35] is the sub-list for method output_type
	7,  // [7:21] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_automationv1_automation_proto_init() }
func file_proto_automationv1_automation_proto_init() {
	if File_proto_automationv1_automation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_automationv1_automation_proto_rawDesc), len(file_proto_automationv1_automation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_automationv1_automation_proto_goTypes,
		DependencyIndexes: file_proto_automationv1_automation_proto_depIdxs,
		MessageInfos:      file_proto_automationv1_automation_proto_msgTypes,
	}.Build()
	File_proto_automationv1_automation_proto = out.File
	file_proto_automationv1_automation_proto_goTypes = nil
	file_proto_automationv1_automation_proto_depIdxs = nil
}
